### PR TITLE
Bugfix/change cloning logic

### LINKED ISSUE #68: Backend: follow-ups for cloning logic
* /upload - very bad, incorrect handling of ResponseEntity. Should be:
  ```kotlin
               .retrieve()
            .toEntity(String::class.java)
            .toMono()
   ```
   Also, for `toMono` kotlin-reqactor-extensions should be added as suggested in spring docs
* Logging: `cloning null project` - incorrect; `projectService.saveProject` should return id of the project so that it can be used in logging

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
* Changed logic
* Added test
* Update build_and_test.yml
* Add jacoco in preprocessor

closes  #68

### CODE REVIEW

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt [hunk 1]
```diff
@@ -35,21 +38,23 @@ class CloneRepositoryController(
      * @return mono string
      */
     @PostMapping(value = ["/submitExecutionRequest"])
-    fun submitExecutionRequest(@RequestBody executionRequest: ExecutionRequest): Mono<ResponseEntity<*>>? {
+    fun submitExecutionRequest(@RequestBody executionRequest: ExecutionRequest): Response {
         val project = executionRequest.project
+        var projectId: String? = null
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt:45]: You can declare it as a non-nullable val, and kotlin compiler allows it because this variable is assigned only once inside `try`

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt [hunk 2]
```diff
@@ -35,21 +38,23 @@ class CloneRepositoryController(
...
         try {
-            projectService.saveProject(project)
-            log.info("Project ${project.id} saved")
+            projectId = projectService.saveProject(project)?.toString() ?: "With non Id"
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt:47]: If project is saved, then an id is assigned to it, so `saveProject` should never return null

**Review by petertrr — CHANGES_REQUESTED** [review]

**Review by petertrr — APPROVED** [review]
