### PR TITLE
Preprocessor: Don't crash if save.properties doesn't exist in the repo

### LINKED ISSUE #274: Preprocessor: Don't crash if save.properties doesn't exist in the repo
In `getTestResourcesRootAbsolutePath` we are reading `save.properties`, which may not exist and it is valid. We should use defaults in this case.

This issue is related to #205, but that one is more general, while this one focuses on a specific bug.

### PR DESCRIPTION
**Pull request by Cheshiriks**
### What's done:
* Added check on save.properties exist
Close #274

### CODE REVIEW

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 1]
```diff
@@ -449,11 +449,14 @@ class DownloadProjectController(private val configProperties: ConfigProperties,
     private fun getTestResourcesRootAbsolutePath(propertiesRelativePath: String,
                                                  projectRootRelativePath: String): String {
         // TODO: File should be provided without explicit naming of `save.propeties`, also
```
Comment (petertrr) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:451]:
```suggestion
        // TODO: File should be provided without explicit naming of `save.propeties`
```

Comment (Cheshiriks) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt]: Fixed

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt [hunk 2]
```diff
@@ -187,6 +187,7 @@ class DockerService(private val configProperties: ConfigProperties) {
                     |RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime
                     |RUN chmod +x $executionDir/$SAVE_AGENT_EXECUTABLE_NAME
                     |RUN chmod +x $executionDir/$SAVE_CLI_EXECUTABLE_NAME
+                    |RUN chmod +x $executionDir/diktat-rules/src/test/resources/test/smoke/src/ktlint
```
Comment (akuleshov7) [inline save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt]: may be we will hardcode it for all binaries?

Comment (Cheshiriks) [reply save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt]: We are running the Save on this branch for testing

Comment (petertrr) [reply save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt]: Yes, we are testing a workaround. Will be implemented properly under #277

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt [hunk 3]
```diff
@@ -187,6 +187,7 @@ class DockerService(private val configProperties: ConfigProperties) {
                     |RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime
                     |RUN chmod +x $executionDir/$SAVE_AGENT_EXECUTABLE_NAME
                     |RUN chmod +x $executionDir/$SAVE_CLI_EXECUTABLE_NAME
+                    |RUN chmod +x $executionDir/diktat-rules/src/test/resources/test/smoke/ktlint
```
Comment (petertrr) [inline save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt:190]: Pls change it to safe call (e.g. `if [ -f <path> ]` or `find -exec`), so that if there is no ktlint file, build doesn't fail. Also, pls add a comment that this is a temporary workaround link to #277 . This way we will be able to run diktat tests while #277 is still WIP.

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt [hunk 4]
```diff
@@ -183,10 +183,12 @@ class DockerService(private val configProperties: ConfigProperties) {
             imageName = imageName(execution.id!!),
             baseDir = resourcesPath,
             resourcesPath = executionDir,
+            // TODO: find ktlint this is a temporary workaround link to #277
             runCmd = """RUN apt-get update && env DEBIAN_FRONTEND="noninteractive" apt-get install -y libcurl4-openssl-dev tzdata && rm -rf /var/lib/apt/lists/*
                     |RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime
                     |RUN chmod +x $executionDir/$SAVE_AGENT_EXECUTABLE_NAME
                     |RUN chmod +x $executionDir/$SAVE_CLI_EXECUTABLE_NAME
+                    |RUN find $executionDir/diktat-rules/src/test/resources/test/smoke/ktlint -type f -exec chmod +x {} \;
```
Comment (petertrr) [inline save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt:191]:
```suggestion
                    |RUN find . -name $executionDir/diktat-rules/src/test/resources/test/smoke/ktlint -type f -exec chmod +x {} \;
```
I tried your command, and it returns 1 if no files have been found. This will cause the entire docker build to fail

**Review by petertrr — CHANGES_REQUESTED** [review]

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt (hunk 4 above)
Comment (Cheshiriks) [reply save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt]: fixed

**Review by petertrr — APPROVED** [review]
