### PR TITLE
Fix timestamp in `/files/list`

### LINKED ISSUE #248: `NoSuchFileException` after selecting a file from frontend
```
/home/cnb/files/1630487894369/ktlint; nested exception is java.nio.file.NoSuchFileException: /home/cnb/files/1630487894369/ktlint
```
But this file has been returned by `/files/list`.

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Changed logic
* Skip `logging:` lines in docker-compose.yaml in `dev` profile
* Add `FileSystemRepository.delete` method

Closes #248

### CODE REVIEW

File: save-backend/src/main/kotlin/org/cqfn/save/backend/repository/FileSystemRepository.kt [hunk 1]
```diff
@@ -101,4 +101,21 @@ class FileSystemRepository(configProperties: ConfigProperties) {
...
     }
+
+    /**
+     * Delete a file described by [fileInfo]
+     *
+     * @param fileInfo a [FileInfo] describing a file to be deleted
+     * @return true if file has been deleted successfully, false otherwise
+     */
+    fun delete(fileInfo: FileInfo) = try {
+        Files.delete(fileInfo.getPath())
```
Comment (akuleshov7) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/repository/FileSystemRepository.kt:112]: why do we need to delete the file first and after that to delete a directory?

**Review by akuleshov7 — APPROVED** [review]

File: save-backend/src/main/kotlin/org/cqfn/save/backend/repository/FileSystemRepository.kt (hunk 1 above)
Comment (petertrr) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/repository/FileSystemRepository.kt]: Fixed
