### PR TITLE
Frontend: Display execution status icon

### LINKED ISSUE #196: Frontend: mark failed and passed executions with symbol and color

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Added icon
* Fixed serverPaging request
* Refactor deserialization from Fetch API
* Fix /latestExecution when there are no executions

Closes #196

### CODE REVIEW

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt [hunk 1]
```diff
@@ -42,14 +44,21 @@ external interface HistoryProps : RProps {
...
+    @Suppress(
+        "TOO_LONG_FUNCTION",
+        "MAGIC_NUMBER",
+        "ForbiddenComment",
+        "LongMethod")
     override fun RBuilder.render() {
         child(tableComponent(
             columns = columns {
-                column("index", "#") {
+                column("result", "") {
```
Comment (kentr0w) [inline save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt:55]: Maybe color all row, not just one cell?

**Review by kentr0w — APPROVED** [review]
lgtm

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt (hunk 1 above)
Comment (petertrr) [reply save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt:56]: Thanks for suggestion, added
