### PR TITLE
Show history in frontend

### LINKED ISSUE #61: Frontend: Populate different views with data from backend
Add queries in
* [ ] history view (also will need to support storing aggregated test results in DB, associated with individual Executions). Also, href from ProjectView, which opens HistoryView on submission, is broken: opens `/history` instead of `#/owner/name/history`
* [x] execution view (#124, #123)
* [x] project dashboard (#72)

This issue can be split into smaller ones if needed.

Queries should take place in `componentDidMount` function and update state

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
- Changed execution entity
- Added logic to view history
- Added request to backend to take history information

Closes #61

### CODE REVIEW

File: save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Agent.kt [hunk 1]
```diff
@@ -14,7 +14,7 @@ import javax.persistence.ManyToOne
 class Agent(
     var containerId: String,
 
-    @ManyToOne(fetch = FetchType.LAZY)
+    @ManyToOne(fetch = FetchType.EAGER)
```
Comment (petertrr) [inline save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Agent.kt:17]: Why did you change it? Absence of this field should be fixed by applying `@Transactional` when necessary

File: save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt [hunk 2]
```diff
@@ -51,15 +60,28 @@ class TestExecutionService(private val testExecutionRepository: TestExecutionRep
...
      * @return list of lost tests
      */
+    @Suppress("TOO_MANY_LINES_IN_LAMBDA")
     fun saveTestResult(testExecutionsDtos: List<TestExecutionDto>): List<TestExecutionDto> {
         val lostTests: MutableList<TestExecutionDto> = mutableListOf()
+        val execution = agentRepository
+            .findByIdOrNull(testExecutionsDtos.first().agentId)  // we take agent id only from first element, because all test executions have same execution
+            ?.execution
+            ?: run {
+                log.error("Agent with id=[${testExecutionsDtos.first().agentId}] was not found in the DB")
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt:70]:
```suggestion
                log.error("Agent with id=[${testExecutionsDtos.first().agentId}] was not found in the DB or doesn't have valid execution")
```
This is also possible here?

File: save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt [hunk 3]
```diff
@@ -51,15 +60,28 @@ class TestExecutionService(private val testExecutionRepository: TestExecutionRep
...
+                return lostTests
+            }
         testExecutionsDtos.forEach { testExecDto ->
             val foundTestExec = testExecutionRepository.findById(testExecDto.id)
             foundTestExec.ifPresentOrElse({
                 it.run {
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt:76]: I didn't think about it before, but it's a very strange statement here: we immediately swap `it` for `this` without any obvious improvements. Maybe, we should remove this `run`?

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt [hunk 4]
```diff
@@ -42,36 +50,45 @@ class HistoryView : RComponent<HistoryProps, RState>() {
                         +"${it.row.index}"
                     }
                 }
-                column("date", "Date") {
+                column("status", "Status") {
```
Comment (petertrr) [inline save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt:53]: We should still have a column for date, I think we can use execution end time

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt [hunk 5]
```diff
@@ -42,36 +50,45 @@ class HistoryView : RComponent<HistoryProps, RState>() {
...
-                json("date" to "26-Jan-2016", "passed" to "26", "failed" to "17", "skipped" to "36"),
-                json("date" to "76-Jun-2019", "passed" to "67", "failed" to "75", "skipped" to "236"),
+
+            post(
+                url = "${window.location.origin}/executionDtoByProject",
+                headers = Headers().also {
+                    it.set("Accept", "application/json")
+                    it.set("Content-Type", "application/json")
+                },
+                body = JSON.stringify(getProject(props.name, props.owner))
```
Comment (petertrr) [inline save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt:82]: Can we make `executionDtoByProject` accept name and owner? This way we will make one query to backend instead of two, and backend can query the whole project on its own

**Review by petertrr — CHANGES_REQUESTED** [review]

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt [hunk 6]
```diff
@@ -42,4 +43,18 @@ class ExecutionController(private val executionService: ExecutionService) {
             executionService.getExecutionDto(executionId)?.let {
                 ResponseEntity.status(HttpStatus.OK).body(it)
             } ?: ResponseEntity.status(HttpStatus.NOT_FOUND).build()
+
+    /**
+     * @param name
+     * @param owner
+     * @return list of execution dtos
+     */
+    @GetMapping("/executionDtoByNameAndOwner")
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt:52]:
```suggestion
    @GetMapping("/executionDtoList")
```
I don't think specifying parameters in method name is good here, it's more important that we get several objects, not just one

File: save-backend/src/main/kotlin/org/cqfn/save/backend/repository/ExecutionRepository.kt [hunk 7]
```diff
@@ -1,10 +1,17 @@
...
  * Repository of execution
  */
 @Repository
-interface ExecutionRepository : BaseEntityRepository<Execution>
+interface ExecutionRepository : BaseEntityRepository<Execution> {
+    /**
+     * @param project
+     * @return list of executions
+     */
+    fun getAllByProject(project: Project): List<Execution>
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/repository/ExecutionRepository.kt:16]:
```suggestion
    fun getAllByProjectNameAndProjectOwner(name: String, owner: String): List<Execution>
```
I think spring-data allows to write what we need in one call

File: save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt [hunk 8]
```diff
@@ -48,11 +52,17 @@ class Execution(
...
+    var failedTests: Long,
+
+    var skippedTests: Long,
 
 ) : BaseEntity() {
     /**
      * @return Execution dto
      */
-    fun toDto() = ExecutionDto(status, type, version)
+    fun toDto() = ExecutionDto(status, type, version, endTime?.format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")), passedTests, failedTests, skippedTests)
```
Comment (petertrr) [inline save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt:67]: Why do we have endTime as String in DTO? I would expect it to be Long timestamp, or some serializable class from kx.datetime

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestExecutionController.kt [hunk 9]
```diff
@@ -49,6 +49,7 @@ class TestExecutionController(private val testExecutionService: TestExecutionSer
      * @return response
      */
     @PostMapping(value = ["/saveTestResult"])
+    @Transactional
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestExecutionController.kt:52]: Why do we need transactional here? It seems that this controller is not affected in this PR anywhere else

Comment (kentr0w) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/TestExecutionController.kt:52]: Yes, but I changed tests for this request and forgot to remove it.

File: save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt (hunk 8 above)
Comment (kentr0w) [reply save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt:67]: Because we use it only in front-end and I thought, to avoid problem with cast use `endTime` as `String`

Comment (petertrr) [reply save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt:67]: Usually timestamp is a more universal representation, which will be converted to the desired format on frontend without the need to parse string in another format

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt [hunk 10]
```diff
@@ -42,4 +43,18 @@ class ExecutionController(private val executionService: ExecutionService) {
...
                 ResponseEntity.status(HttpStatus.OK).body(it)
             } ?: ResponseEntity.status(HttpStatus.NOT_FOUND).build()
+
+    /**
+     * @param name
+     * @param owner
+     * @return list of execution dtos
+     */
+    @GetMapping("/executionDtoList")
+    @Transactional
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/ExecutionController.kt:53]: I think `@Transactional` is redundant now

File: save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt (hunk 8 above)
Comment (petertrr) [reply save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/Execution.kt:67]: BTW, we already have `org.cqfn.save.utils.LocalDateTimeSerializer` to make it easier to convert `LocalDateTime` to timestamp.

**Comment by petertrr** [comment]
@kentr0w , also there is a problem, related to histroy view, as stated in the issue:

> Also, href from ProjectView, which opens HistoryView on submission, is broken: opens /history instead of #/owner/name/history

Please fix it in this PR as well

File: save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt [hunk 11]
```diff
@@ -56,7 +57,11 @@ class HistoryView : RComponent<HistoryProps, RState>() {
                 }
                 column("date", "Date") {
                     td {
-                        +(it.value.endTime ?: "RUNNING")
+                        +(it.value.endTime?.let {
+                            Instant.fromEpochSeconds(it.toString().toLong())  // there is some bug with parse endTime to Instant - that why this crutch
```
Comment (petertrr) [inline save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/HistoryView.kt:61]: How does `Long.toString().toLong()` help? What exactly was the bug?

**Review by petertrr — APPROVED** [review]
