### PR TITLE
Preprocessor: Discover test resources

### LINKED ISSUE #105: Preprocessor: Discover tests and test suites using save-core
Now there are two stubs, `getAllTestSuites` and `getAllTests`. This issue depends on https://github.com/cqfn/save/pull/63 (available since `0.1.0-alpha.3`). If the provided project doesn't have valid SAVE configuration (i.e. ConfigDetector or discoverTestFiles throw exceptions), then the whole execution should be postponed and marked as Failed.

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Added dependency on save-common and save-core
* Implemented logic in TestDiscoveringService
* Use snapshot version of SAVE
* Added tests

Closes #105 

Depends on ~https://github.com/cqfn/save/pull/72~

### TODO:
* Snapshot version of SAVE CLI (or we could decide, that we only need snapshot version to integrate with the new API, and actual execution will always use release version) (#134)
* [x] https://github.com/cqfn/save/issues/104
* Incompatible ABI in kotlinx.datetime breaks compilation in Agent; can be worked around by excluding datetime, because we don't use it

### CODE REVIEW

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 1]
```diff
@@ -168,69 +178,94 @@ class DownloadProjectController(private val configProperties: ConfigProperties)
...
         executionType: ExecutionType,
-        testSuitesDto: List<TestSuiteDto>?
+        testSuiteDtos: List<TestSuiteDto>?
     ) {
-        testSuitesDto?.let {
-            require(executionType == ExecutionType.STANDARD)
-        } ?: require(executionType == ExecutionType.GIT)
+        testSuiteDtos?.let {
+            require(executionType == ExecutionType.STANDARD) { "Test suites shouldn't be provided unless ExecutionType is STANDARD (actual: $executionType)" }
+        } ?: require(executionType == ExecutionType.GIT) { "Test suites are not provided, but should for executionType=$executionType" }
```
Comment (kentr0w) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:187]: Do we really need this `require`, if we have verification in frontend to pass only one type of project?

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 2]
```diff
@@ -168,69 +178,94 @@ class DownloadProjectController(private val configProperties: ConfigProperties)
     private fun sendToBackendAndOrchestrator(
         project: Project,
         propertiesRelativePath: String,
-        resourcesRootPath: String,
+        resourcesRootRelativePath: String,
```
Comment (kentr0w) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:181]: Here it isn't path to resources

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 3]
```diff
@@ -157,7 +161,13 @@ class DownloadProjectController(private val configProperties: ConfigProperties)
...
 
     /**
-     * We have not null list of TestSuite only, if execute type is STANDARD ()
+     * Note: We have not null list of TestSuite only, if execute type is STANDARD ()
+     *
+     * - Post request to backend to create PENDING executions
+     * - Discover all test suites in the cloned project
+     * - Post request to backend to save all test suites
+     * - Discover all tests in the cloned project
+     * - Post request to backend to save all tests and create TestExecutions for them
```
Comment (kentr0w) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:170]: What about `initializeAgent`?

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 4]
```diff
@@ -168,69 +178,94 @@ class DownloadProjectController(private val configProperties: ConfigProperties)
...
+    }
+
+    private fun discoverAndSaveTestSuites(project: Project,
+                                          testResourcesRootPath: String,
+                                          propertiesRelativePath: String): Mono<List<TestSuite>> {
+        val testSuites: List<TestSuiteDto> = try {
+            testDiscoveringService.getAllTestSuites(project, testResourcesRootPath, propertiesRelativePath)
+        } catch (iae: IllegalArgumentException) {
+            log.error("Couldn't discover test suites, aborting: ", iae)
+            throw iae
```
Comment (kentr0w) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:222]: Why do you throw an exception?

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 5]
```diff
@@ -168,69 +178,94 @@ class DownloadProjectController(private val configProperties: ConfigProperties)
...
+                    }
+            }
+            .subscribe()
+    }
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun getTestResourcesRootAbsolutePath(propertiesRelativePath: String,
+                                                 resourcesRootRelativePath: String): String {
+        val saveProperties: SaveProperties = decodeFromPropertiesFile(
+            File(configProperties.repository, resourcesRootRelativePath)
```
Comment (kentr0w) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:207]: If i correctly understand, `resourcesRootRelativePath` is path to project, you need to exctract property fro project by its path?

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 6]
```diff
@@ -168,69 +178,94 @@ class DownloadProjectController(private val configProperties: ConfigProperties)
...
+                            .then(initializeAgents(execution, executionId))
+                    }
+            }
+            .subscribe()
+    }
+
+    @Suppress("UnsafeCallOnNullableType")
+    private fun getTestResourcesRootAbsolutePath(propertiesRelativePath: String,
+                                                 resourcesRootRelativePath: String): String {
+        val saveProperties: SaveProperties = decodeFromPropertiesFile(
```
Comment (kentr0w) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:206]: What if there isn't `save.properties` file?

**Review by kentr0w — CHANGES_REQUESTED** [review]

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt (hunk 6 above)
Comment (petertrr) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:206]: Then, the `FileNotFoundException` will be thrown and the job in subscription will be stopped. I believe, I should also mark execution as failed on such errors

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt (hunk 1 above)
Comment (petertrr) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:187]: I believe, additional validation won't hurt, since we don't have good integration tests or tests on frontend yet

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt (hunk 2 above)
Comment (petertrr) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:181]: Yes, fixed

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt (hunk 5 above)
Comment (petertrr) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:207]: `propertiesRelativePath` is relative to project root, so there is no need to extract anything else

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt (hunk 3 above)
Comment (petertrr) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:170]: фввув

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt (hunk 4 above)
Comment (petertrr) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:222]: Removed in favor of common error handler

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt (hunk 6 above)
Comment (petertrr) [reply save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:213]: Added a `doOnError` block in mono

**Review by kentr0w — APPROVED** [review]
lgtm
