### PR TITLE
Preprocessor: fixes for test discovery

### LINKED ISSUE #147: Issues with test discovering
* [x] Each test has *two* test_executions - reason is a bug with `File.toHash`
  test_execution:
| id | | | | | |
| --- | --- | --- | --- | --- | --- |
| 1 | 1 |   | 2 | READY |   |  
2 | 1 |   | 2 | READY |   |  
3 | 1 |   | 3 | READY |   |  
4 | 1 |   | 3 | READY |   |  
5 | 1 |   | 5 | READY |   |  
6 | 1 |   | 5 | READY |   |  
7 | 1 |   | 6 | READY |   |  
8 | 1 |   | 6 | READY |   |  
* [x] We shouldn't save test suites that are already present in backend's TestSuitesService:
1 | stub | PROJECT | 1 | Jun 22, 2021, 5:13:31 PM | save.properties
-- | -- | -- | -- | -- | --
2 | autofix | PROJECT | 1 | Jun 22, 2021, 5:58:44 PM | save.properties
3 | smoke tests | PROJECT | 1 | Jun 22, 2021, 5:58:44 PM | save.properties
4 | warnings | PROJECT | 1 | Jun 22, 2021, 5:58:44 PM | save.properties
5 | DocsCheck | PROJECT | 1 | Jun 22, 2021, 5:58:44 PM | save.properties
6 | autofix | PROJECT | 1 | Jun 22, 2021, 6:14:06 PM | save.properties
7 | smoke tests | PROJECT | 1 | Jun 22, 2021, 6:14:06 PM | save.properties
8 | warnings | PROJECT | 1 | Jun 22, 2021, 6:14:06 PM | save.properties
9 | DocsCheck | PROJECT | 1 | Jun 22, 2021, 6:14:06 PM | save.properties
10 | autofix | PROJECT | 1 | Jun 22, 2021, 7:17:16 PM | save.properties
11 | smoke tests | PROJECT | 1 | Jun 22, 2021, 7:17:16 PM | save.properties
12 | warnings | PROJECT | 1 | Jun 22, 2021, 7:17:16 PM | save.properties
13 | DocsCheck | PROJECT | 1 | Jun 22, 2021, 7:17:16 PM | save.properties
14 | autofix | PROJECT | 1 | Jun 23, 2021, 1:18:29 PM | save.properties
15 | smoke tests | PROJECT | 1 | Jun 23, 2021, 1:18:29 PM | save.properties
16 | warnings | PROJECT | 1 | Jun 23, 2021, 1:18:29 PM | save.properties
17 | DocsCheck | PROJECT | 1 | Jun 23, 2021, 1:18:29 PM | save.properties
* [x] Only one test is discovered in `save/examples/kotlin-diktat` - same, because of bug with `File.toHash`:
  1 | /home/cnb/repositories/-870706772/examples/kotlin-diktat/fix/smoke/Example1Expected.kt | d41d8cd98f00b204e9800998ecf8427e | Jun 22, 2021, 5:58:44 PM | 3

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Check test suites before saving
* Fix file hash calculation
* More logging regarding tests discovery
* Removed deprecated LogContainerCallback
* Added more tests

Closes #147

### CODE REVIEW

File: save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt [hunk 1]
```diff
@@ -16,12 +17,28 @@ class TestSuitesService {
...
      */
+    @Suppress("UnsafeCallOnNullableType")
     fun saveTestSuite(testSuitesDto: List<TestSuiteDto>): List<TestSuite> {
-        val testSuites = testSuitesDto.map { TestSuite(it.type, it.name, it.project, LocalDateTime.now(), "save.properties") }
-        testSuiteRepository.saveAll(testSuites)
-        return testSuites
+        val testSuites = testSuitesDto
+            .map { TestSuite(it.type, it.name, it.project, null, "save.properties") }
+            .map { testSuite ->
+                // try to find TestSuite in the DB based on all non-null properties of `testSuite`
```
Comment (Cheshiriks) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt:30]: I think this logic is best done in the database itself. Add a primary key to a bunch of fields: type + name + project + properties

Comment (petertrr) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt:30]: You mean like a composite key of four fields? What about id then? And the main advantage of your approach would be that we can call `saveAll` without additional checks before? I think for a relatively small number of queries (there usually will be not many test suites), such change would introduce to much complexity: managing composite key in hibernate, updating DB schema every time we add a new field in this class etc.

Comment (Cheshiriks) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestSuitesService.kt:30]: Yes, I agree. This is probably better

**Review by Cheshiriks — APPROVED** [review]
