### PR TITLE
Save execution before all

### LINKED ISSUE #155: Execution should be created right after request submission
Now execution is created only after successful downloading of repo => user doesn't see it after submission of frontend. Also, if preprocessor fails to download resources, it is not stored in history in any way.

### PR DESCRIPTION
**Pull request by kentr0w**
### What's done:
- Changed logic to save execution before all
- Changed logic in preprocessor to update execution
- Added tests
- Closes #155

### CODE REVIEW

File: save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionUpdateCreationDto.kt [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+/**
+ * @property project
+ * @property testSuiteIds
+ * @property resourcesRootPath
+ * @property batchSize
+ * @property version
+ */
+@Serializable
+data class ExecutionUpdateCreationDto(
```
Comment (petertrr) [inline save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionUpdateCreationDto.kt:14]:
```suggestion
data class ExecutionInitializationDto(
```
or someting similar? Execution is already created by the time this class is used

File: save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt [hunk 2]
```diff
@@ -214,10 +217,9 @@ class DownloadProjectController(private val configProperties: ConfigProperties)
             require(executionType == ExecutionType.STANDARD) { "Test suites shouldn't be provided unless ExecutionType is STANDARD (actual: $executionType)" }
         } ?: require(executionType == ExecutionType.GIT) { "Test suites are not provided, but should for executionType=$executionType" }
 
-        val execution = Execution(project, LocalDateTime.now(), null, ExecutionStatus.PENDING, "ALL",
-            projectRootRelativePath, 0, configProperties.executionLimit, executionType, executionVersion, 0, 0, 0)
-        webClientBackend.makeRequest(BodyInserters.fromValue(execution), "/createExecution") { it.bodyToMono<Long>() }
-            .flatMap { executionId ->
+        val executionUpdate = ExecutionUpdateCreationDto(project, "ALL", projectRootRelativePath, configProperties.executionLimit, executionVersion)
+        webClientBackend.makeRequest(BodyInserters.fromValue(executionUpdate), "/updateNewExecution") { it.bodyToMono<Execution>() }
+            .flatMap { exec ->
```
Comment (petertrr) [inline save-preprocessor/src/main/kotlin/org/cqfn/save/preprocessor/controllers/DownloadProjectController.kt:222]:
```suggestion
            .flatMap { execution ->
```

File: db/changelog/v-1/06-chageset-execution-table.xml [hunk 3]
```diff
@@ -22,28 +22,28 @@
                 <constraints nullable="false"/>
             </column>
             <column name="end_time" type="timestamp">
-                <constraints nullable="false" />
+                <constraints nullable="true" />
```
Comment (petertrr) [inline db/changelog/v-1/06-chageset-execution-table.xml:25]: @aktsay6 insisted very much, that this field should be not nullable, because we will not read it until execution status changes to `finish` :) But, I guess, since we are making all other fields nullable, it doesn't matter

**Review by petertrr — CHANGES_REQUESTED** [review]

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt [hunk 4]
```diff
@@ -42,11 +48,16 @@ class CloneRepositoryController(
      * @param executionRequest information about project
      * @return mono string
      */
+    @Suppress("TOO_MANY_LINES_IN_LAMBDA")
     @PostMapping(value = ["/submitExecutionRequest"])
     fun submitExecutionRequest(@RequestBody executionRequest: ExecutionRequest): Mono<StringResponse> {
         val projectExecution = executionRequest.project
         val project = projectService.getProjectByNameAndOwner(projectExecution.name, projectExecution.owner)
         return project?.let {
+            val execution = Execution(project, LocalDateTime.now(), null, ExecutionStatus.PENDING, null,
```
[the remark this answers is not in the document]
Comment (kentr0w) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt:57]: I moved it into another method to save execution in backend.

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt [hunk 5]
```diff
@@ -75,6 +84,7 @@ class CloneRepositoryController(
         val projectExecution = executionRequestForStandardSuites.project
         val project = projectService.getProjectByNameAndOwner(projectExecution.name, projectExecution.owner)
         project?.let { proj ->
+            saveExecution(proj, ExecutionType.STANDARD)
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt:87]: You can discard lambda's argument completely and just use `project`, which is smart-casted to non-nullable type inside this scope. I think it improves readability compared to introducing a new name for the same variable. Or just use `it`, likein the first method.

File: save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt [hunk 6]
```diff
@@ -77,4 +80,18 @@ class ExecutionService(private val executionRepository: ExecutionRepository) {
...
     fun getLatestExecutionByProjectNameAndProjectOwner(name: String, owner: String): Execution? =
             executionRepository.findTopByProjectNameAndProjectOwnerOrderByStartTimeDesc(name, owner)
+
+    /**
+     * @param executionInitializationDto execution dto to update
+     * @return execution
+     */
+    fun updateNewExecution(executionInitializationDto: ExecutionInitializationDto) =
+            executionRepository.findTopByProjectOrderByStartTimeDesc(executionInitializationDto.project)?.let {
+                assert(it.version == null) { "Execution was already updated" }
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/service/ExecutionService.kt:90]: Use `require` on something similar for preconditions; it's better suited for this than JVM-specific `assert`. Also, you still need `-ea` flag even for newer JVMs to enable asserts

File: save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionInitializationDto.kt [hunk 7]
```diff
@@ -0,0 +1,20 @@
+package org.cqfn.save.execution
+
+import org.cqfn.save.entities.Project
+import kotlinx.serialization.Serializable
+
+/**
```
Comment (petertrr) [inline save-cloud-common/src/commonMain/kotlin/org/cqfn/save/execution/ExecutionInitializationDto.kt:6]: Any useful docs for this?

**Review by petertrr — APPROVED** [review]
LGTM, just fix a couple of minor comments
