### PR TITLE
Fixed wrong encode/decode

### LINKED ISSUE #203: Bad request during submit request
`Bad request` alert appears when submitted request

### PR DESCRIPTION
**Pull request by kentr0w**
###What's done:
- Fixed bug
- Closes #203

### CODE REVIEW

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt [hunk 1]
```diff
@@ -104,10 +104,13 @@ class CloneRepositoryController(
...
+    @Suppress("UnsafeCallOnNullableType")
     private fun saveExecution(project: Project, type: ExecutionType, sdk: Sdk): Long {
         val execution = Execution(project, LocalDateTime.now(), null, ExecutionStatus.PENDING, null,
-            null, 0, null, type, null, 0, 0, 0, sdk.toString())
+            null, 0, null, type, null, 0, 0, 0, sdk.toString()).apply {
+            id = executionService.saveExecution(this)
+        }
         log.info("Creating a new execution id=${execution.id} for project id=${project.id}")
-        return executionService.saveExecution(execution)
+        return execution.id!!
```
Comment (petertrr) [inline save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt:114]: Was there an issue here? I believe, spring-data returns the saved object with id. What's the difference with old version here?

**Review by petertrr — APPROVED** [review]

File: save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt (hunk 1 above)
Comment (kentr0w) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt:114]: Yes, you're right. But in `log.info ()`, before saving, GHHs id is still `null`

Comment (petertrr) [reply save-backend/src/main/kotlin/org/cqfn/save/backend/controllers/CloneRepositoryController.kt:114]: Oh, ok
