### PR TITLE
Orchestrator: Fixes for agents shutdown logic

### LINKED ISSUE #145: Orchestrator: Agent statuses and Execution status are not updated after execution end
* [x] Execution is not marked after shutdown.
* [x] AgentState isn't updated: agents are still `IDLE` after shutdown.
* [x] Logging is not clear, when atomic flag for agents stop is already set

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Execution and AgentsStatus are marked as FINISHED after agents shutdown
* Enabled debug for save-agent
* Fix property file path in backend saveTestSuite
* Added inputs for code generation tasks in gradle
* Added more logging for TestDiscoveringService, enabled debug logging in application.properties
* Publish agent's version instead of cli version

Closes #145

### CODE REVIEW

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt [hunk 1]
```diff
@@ -52,16 +52,10 @@ class HeartbeatController(private val agentService: AgentService,
         )
             .then(
                 when (heartbeat.state) {
-                    AgentState.IDLE -> agentService.getNewTestsIds(heartbeat.agentId).subscribeOn(scheduler)
+                    AgentState.IDLE -> agentService.getNewTestsIds(heartbeat.agentId)
```
Comment (kentr0w) [inline save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt:55]: Why did you remove `subscribeOn`?

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt [hunk 2]
```diff
@@ -80,17 +81,27 @@ class DockerService(private val configProperties: ConfigProperties) {
...
+                try {
+                    agentIds.forEach {
+                        log.info("Stopping agent with id=$it")
+                        containerManager.dockerClient.stopContainerCmd(it).exec()
+                        log.info("Agent with id=$it has been stopped")
+                    }
+                    true
+                } catch (dex: DockerException) {
+                    log.error("Error while stopping agents $agentIds", dex)
+                    false
```
Comment (kentr0w) [inline save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt:97]: Do we need to do something else to stop container?

File: save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/AgentStatus.kt [hunk 3]
```diff
@@ -42,8 +42,19 @@ class AgentStatus(
...
     val containerId: String,
 )
+
+/**
+ * Statuses of a group of agents for a single Execution
+ *
+ * @property executionId id of Execution
+ * @property agentStatuses list of [AgentStatusDto]s
+ */
+data class AgentStatusesForExecution(
```
Comment (kentr0w) [inline save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/AgentStatus.kt:57]: May be just add `executionId` to `AgentStatusDto` to avoid new class?

**Review by kentr0w — CHANGES_REQUESTED** [review]

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt (hunk 1 above)
Comment (petertrr) [reply save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/controller/HeartbeatController.kt:55]: Because it's a little refactored now: before we were adding a blocking handler for the returned Mono, which was executed on `sheduler`. Now we make another request inside `doOnSuccess` and subscribe on *that* request on `scheduler`.

File: save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt (hunk 2 above)
Comment (petertrr) [reply save-orchestrator/src/main/kotlin/org/cqfn/save/orchestrator/service/DockerService.kt:97]: There are two documented types of `DockerException` here: 
```java
     * @throws NotFoundException
     *             No such container
     * @throws NotModifiedException
     *             Container already stopped
```
Both of them seem to indicate that we shouldn't try to stop it again. And even if the container haven't been stopped, it will continue to send heartbeats and we will continue to try to stop it.

File: save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/AgentStatus.kt (hunk 3 above)
Comment (petertrr) [reply save-cloud-common/src/jvmMain/kotlin/org/cqfn/save/entities/AgentStatus.kt:57]: I think this class can more clearly indicate, that all agents have the same `executionId` here, and also removes a little of data duplication.

**Review by kentr0w — APPROVED** [review]
lgtm
